/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { apiClient } from '../../lib/axios';




/**
 * @summary Authenticated Route
 */
export const authenticatedRouteAuthenticatedRouteGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/authenticated-route`, method: 'GET', signal
    },
      );
    }
  

export const getAuthenticatedRouteAuthenticatedRouteGetQueryKey = () => {
    return [`/authenticated-route`] as const;
    }

    
export const getAuthenticatedRouteAuthenticatedRouteGetQueryOptions = <TData = Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthenticatedRouteAuthenticatedRouteGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>> = ({ signal }) => authenticatedRouteAuthenticatedRouteGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthenticatedRouteAuthenticatedRouteGetQueryResult = NonNullable<Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>>
export type AuthenticatedRouteAuthenticatedRouteGetQueryError = unknown


export function useAuthenticatedRouteAuthenticatedRouteGet<TData = Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>,
          TError,
          Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthenticatedRouteAuthenticatedRouteGet<TData = Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>,
          TError,
          Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthenticatedRouteAuthenticatedRouteGet<TData = Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Authenticated Route
 */

export function useAuthenticatedRouteAuthenticatedRouteGet<TData = Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authenticatedRouteAuthenticatedRouteGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthenticatedRouteAuthenticatedRouteGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



